# mapping known values for Springer resourceType and genre to something sort of normalized 
GENRES = {
    "": [],
    "Atlas": ["Atlas"],
    "Bibliography": ["Bibliography"],
    "Biography": ["Biography"],
    "Booklet": ["Booklet"],
    "Brief": ["Brief"],
    "Collected works": ["Collected works"],
    "Collection of essays": ["Collection of essays"],
    "Commemorative publication": ["Commemorative publication"],
    "Contributed Volume": ["Contributed volume"],
    "Contributed volume": ["Contributed volume"],
    "Data software": ["Data software"],
    "Dictionary": ["Dictionary"],
    "Educational supplement": ["Educational supplement"],
    "Encyclop(a)edia": ["Encyclopedia"],
    "General interest": ["General interest"],
    "German  textbook": ["Textbook", "German textbook"],
    "German textbook": ["Textbook", "German textbook"],
    "Graduate Textbooks": ["Textbook", "Graduate textbook"],
    "Graduate/advanced undergraduate ": ["Textbook", "Graduate textbook", "Undergraduate textbook"],
    "Graduate/advanced undergraduate textbook": ["Textbook", "Graduate textbook", "Undergraduate textbook"],
    "Handbook": ["Handbook"],
    "Highschool textbook": ["Textbook", "Highschool textbook"],
    "Highschool textbook": ["Textbook", "Highschool textbook"],
    "Laboratory book": ["Laboratory book"],
    "Loose-leaf publication": ["Loose-leaf publication"],
    "Manual": ["Manual"],
    "Marketing service;galleys": ["Galleys"],
    "Monograph": ["Monograph"],
    "Ph.D. Thesis": ["Ph.D. thesis"],
    "Popular science": ["Popular science"],
    "Proceedings": ["Proceedings"],
    "Professional Book": ["Professional book"],
    "Professional book": ["Professional book"],
    "Reference Work": ["Reference work"],
    "Reference work": ["Reference work"],
    "Reviews": ["Reviews"],
    "Solution manual": ["Solution manual"],
    "Special Issue": ["Special issue"],
    "Teachers manual": ["Teachers manual"],
    "Test": ["Test"],
    "Undergraduate Textbook": ["Textbook", "Undergraduate textbook"],
    "Undergraduate textbook": ["Textbook", "Undergraduate textbook"],
    "Yearbook": ["Yearbook"],
    "professional book": ["Professional book"],
    "Book ConferencePaper": ["Conference paper"],
    "Book Protocol": ["Protocol"],
    "Book ReferenceWorkEntry": ["Reference work"],
    "Book": [],
    "Protocol Book": ["Protocol"]
}
